# Generated by Django 3.2.3 on 2021-05-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('F', 'Full Set-Up'), ('C', 'Cleaning'), ('N', 'Neck + Truss Rod Adjustment'), ('P', 'Pick-Ups Adjustment'), ('S', 'New Strings')], default='F', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
        ),
    ]
