# Generated by Django 3.2.3 on 2021-05-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('B', 'Body'), ('N', 'Neck'), ('F', 'Fingerboard')], max_length=1)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='setup',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='setup',
            name='date',
            field=models.DateField(verbose_name='Set-Up Date'),
        ),
    ]
