# Generated by Django 3.2.3 on 2021-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210519_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='woods',
            field=models.ManyToManyField(to='main_app.Wood'),
        ),
    ]
